sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: true
before_script:
  - npm prune
script:
  - npm run test    
after_success:
  - npm run semantic-release        
